### ISSUE TITLE
MainState is not defined

### ISSUE THREAD

**Issue by kazy-dev** [alberdev/EmptyStateKit#4]
<img width="860" alt="スクリーンショット 2019-07-30 9 19 48" src="https://user-images.githubusercontent.com/22549154/62091345-5400c880-b2ab-11e9-940c-43b7c48f8d9a.png">
implemented according to the implementation method of Using EmptyStateDataSource in README, but MainState is not defined.
Please define MainState.
Xcode10.2
EmptyStateKit 1.0.7

**Comment by kazy-dev** [comment]
I'm sorry. MainState did not notice that the implementer defined a new one.
It would be appreciated if you could write in detail in the README so as not to make a mistake like me.
We apologize for the inconvenience, but thank you.

**Comment by kazy-dev** [comment]
I'm sorry. MainState did not notice that the implementer defined a new one.
Please close this issue.

**Comment by alberdev** [comment]
👍  Thank you anyway!
